kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{ include "cert-manager-csi-driver.labels" . | nindent 4 }}
  name: {{ include "cert-manager-csi-driver.name" . }}
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["watch", "create", "delete", "list"]
{{- if and (.Capabilities.APIVersions.Has "security.openshift.io/v1") (.Values.openshift.securityContextConstraint.enabled) }}
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: [{{ .Values.openshift.securityContextConstraint.name | quote }}]
  verbs: ["use"]
{{- end }}